const lessonTitle = "一毛不拔";

const lessonData = [
    // ===== 第1段 =====
    ["一猴", "yī hóu", "A monkey", "Seekor monyet", "一只猴子"],
    ["死", "sǐ", "died", "mati", "死了"],
    ["，", "", "", "", ""],
    ["见", "jiàn", "met", "berjumpa", "拜见"],
    ["冥王", "míng wáng", "the King of Hell", "Raja Neraka", "阎王"],
    ["，", "", "", "", ""],
    ["求", "qiú", "begged", "memohon", "请求"],
    ["转人身", "zhuǎn rén shēn", "to be reborn as a human", "dilahirkan semula sebagai manusia", "转世做人"],
    ["。", "", "", "", ""],
    ["王曰", "wáng yuē", "The King said", "Raja berkata", "阎王说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["既欲", "jì yù", "Since you wish", "Memandangkan kamu ingin", "既然想要"],
    ["做人", "zuò rén", "to be a human", "menjadi manusia", "做人"],
    ["，", "", "", "", ""],
    ["须", "xū", "must", "mesti", "必须"],
    ["将", "jiāng", "have", "menyuruh", "把"],
    ["毛", "máo", "fur", "bulu", "毛发"],
    ["尽", "jìn", "completely", "semuanya", "全部"],
    ["拔去", "bá qù", "plucked out", "dicabut", "拔掉"],
    ["。”", "", "", "", ""],
    ["即", "jí", "immediately", "segera", "立即"],
    ["唤", "huàn", "summoned", "memanggil", "叫来"],
    ["夜叉", "yè chā", "a yaksha", "Yaksha", "夜叉"],
    ["拔之", "bá zhī", "to pluck it", "mencabutnya", "拔它的毛"],
    ["。", "", "", "", ""],
    ["方", "fāng", "Just as", "Baru sahaja", "刚刚"],
    ["拔", "bá", "plucked", "mencabut", "拔"],
    ["一根", "yī gēn", "one strand", "sehelai", "一根"],
    ["，", "", "", "", ""],
    ["猴", "hóu", "the monkey", "monyet", "猴子"],
    ["不胜", "bù shèng", "could not bear", "tidak tahan", "禁不住"],
    ["痛", "tòng", "pain", "sakit", "疼痛"],
    ["叫", "jiào", "cried out", "menjerit", "叫喊"],
    ["。", "", "", "", ""],
    ["王笑曰", "wáng xiào yuē", "The King laughed and said", "Raja ketawa dan berkata", "阎王笑着说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["看你", "kàn nǐ", "Look at you", "Lihatlah kamu", "看你"],
    ["一毛不拔", "yī máo bù bá", "not willing to pluck a single hair", "tidak rela mencabut sehelai bulu pun", "连一根毛都不肯拔"],
    ["，", "", "", "", ""],
    ["如何", "rú hé", "how", "bagaimana", "怎么"],
    ["做人", "zuò rén", "can you be a human", "boleh menjadi manusia", "做人"],
    ["？”", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["邯郸淳", "hán dān chún", "Handan Chun", "Handan Chun", "邯郸淳"],
    ["《", "", "", "", ""],
    ["一毛不拔", "yī máo bù bá", "Not Plucking a Single Hair", "Tidak Mencabut Sehelai Bulu Pun", "一毛不拔"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
